set_property PACKAGE_PIN G22 [get_ports sys_clk]
set_property PACKAGE_PIN V26 [get_ports spi_clk]
set_property PACKAGE_PIN T18 [get_ports spi_csn]
set_property PACKAGE_PIN AD23 [get_ports o_io_update]
set_property IOSTANDARD LVCMOS25 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS25 [get_ports o_io_update]
set_property IOSTANDARD LVCMOS25 [get_ports spi_csn]
set_property IOSTANDARD LVCMOS25 [get_ports spi_miso]
set_property IOSTANDARD LVCMOS25 [get_ports spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]

set_property PACKAGE_PIN AE26 [get_ports {o_profile_ctrl[0]}]
set_property PACKAGE_PIN K22 [get_ports {o_profile_ctrl[1]}]
set_property PACKAGE_PIN H23 [get_ports {o_profile_ctrl[2]}]
set_property PACKAGE_PIN AC26 [get_ports spi_mosi]
set_property PACKAGE_PIN T19 [get_ports o_io_reset]
set_property PACKAGE_PIN Y20 [get_ports o_master_reset]
set_property IOSTANDARD LVCMOS33 [get_ports {o_profile_ctrl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_profile_ctrl[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {o_profile_ctrl[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports o_io_reset]
set_property IOSTANDARD LVCMOS25 [get_ports o_master_reset]
set_property PACKAGE_PIN U26 [get_ports spi_miso]

set_property PACKAGE_PIN AB26 [get_ports ad9910_ref_clk_p]
set_property PACKAGE_PIN V24 [get_ports ad9910_ref_clk_n]
set_property IOSTANDARD LVCMOS25 [get_ports ad9910_ref_clk_p]
set_property IOSTANDARD LVCMOS25 [get_ports ad9910_ref_clk_n]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets ad9910_ref_clk_p_OBUF_BUFG]
