set_property PACKAGE_PIN F6 [get_ports sys_clk]
set_property PACKAGE_PIN AC26 [get_ports spi_mosi]
set_property PACKAGE_PIN U26 [get_ports spi_miso]
set_property PACKAGE_PIN V26 [get_ports spi_clk]
set_property PACKAGE_PIN T18 [get_ports spi_csn]
set_property PACKAGE_PIN AD23 [get_ports o_io_update]
set_property IOSTANDARD LVCMOS25 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS25 [get_ports o_io_update]
set_property IOSTANDARD LVCMOS25 [get_ports spi_csn]
set_property IOSTANDARD LVCMOS25 [get_ports spi_miso]
set_property IOSTANDARD LVCMOS25 [get_ports spi_mosi]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_in]
connect_debug_port dbg_hub/clk [get_nets sys_clk_IBUF_BUFG]
